"use client";

import { motion, useReducedMotion, useScroll, useTransform } from "motion/react";
import { useRef } from "react";
import { bestVariant, mediaUrl, srcSet, type Media } from "@/lib/media";

/**
 * Hero photograph (used when no hero film is set). Desktop gets a restrained
 * parallax; visitors who prefer reduced motion get a static image.
 */
export function HeroMedia({ image, sizes }: { image: Media | null; sizes: string }) {
  const reduce = useReducedMotion();
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start start", "end start"] });
  const y = useTransform(scrollYProgress, [0, 1], [0, 70]);

  return (
    <div ref={ref} className="absolute inset-0 overflow-hidden bg-cream">
      <motion.div className="absolute inset-[-5%_0] max-lg:!transform-none" style={reduce ? undefined : { y }}>
        {image && (
          // eslint-disable-next-line @next/next/no-img-element -- variants are pre-generated by the media pipeline
          <img
            src={mediaUrl(image, bestVariant(image, 1600))}
            srcSet={srcSet(image)}
            sizes={sizes}
            alt={image.alt}
            width={image.width}
            height={image.height}
            fetchPriority="high"
            decoding="async"
            className="absolute inset-0 h-full w-full object-cover"
            style={{ objectPosition: `${image.focalX}% ${image.focalY}%` }}
          />
        )}
      </motion.div>
    </div>
  );
}
