"use client";

import { useEffect, useRef, useState } from "react";
import { Pause, Play } from "@phosphor-icons/react";
import { motion, useReducedMotion, useScroll, useTransform } from "motion/react";
import { bestVariant, mediaUrl, srcSet, type Media } from "@/lib/media";

export type HeroVideo = { src: string; type: string };

/**
 * Hero photograph or looping video. Video is muted, inline, never blocks the
 * page (poster first, `preload="metadata"`), shows a pause control as WCAG
 * 2.2.2 requires for moving content, and is replaced by the still image for
 * visitors who prefer reduced motion. Desktop gets a restrained parallax.
 */
export function HeroMedia({ image, video, sizes }: { image: Media | null; video: HeroVideo | null; sizes: string }) {
  const reduce = useReducedMotion();
  const ref = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [paused, setPaused] = useState(false);
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start start", "end start"] });
  const y = useTransform(scrollYProgress, [0, 1], [0, 70]);
  const showVideo = !!video && !reduce;
  const poster = image ? mediaUrl(image, bestVariant(image, 1600)) : undefined;

  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    // Pause when off-screen to save battery and data.
    const io = new IntersectionObserver(([e]) => {
      if (!e.isIntersecting) v.pause();
      else if (!paused) void v.play().catch(() => {});
    });
    io.observe(v);
    return () => io.disconnect();
  }, [paused, showVideo]);

  function toggle() {
    const v = videoRef.current;
    if (!v) return;
    if (v.paused) {
      void v.play();
      setPaused(false);
    } else {
      v.pause();
      setPaused(true);
    }
  }

  return (
    <div ref={ref} className="absolute inset-0 overflow-hidden bg-cream">
      <motion.div className="absolute inset-[-5%_0] max-lg:!transform-none" style={reduce ? undefined : { y }}>
        {showVideo ? (
          <video
            ref={videoRef}
            className="absolute inset-0 h-full w-full object-cover"
            style={image ? { objectPosition: `${image.focalX}% ${image.focalY}%` } : undefined}
            autoPlay
            muted
            loop
            playsInline
            preload="metadata"
            poster={poster}
            aria-label={image?.alt ? `Video: ${image.alt}` : "Video of a manicure"}
          >
            <source src={video!.src} type={video!.type} />
          </video>
        ) : image ? (
          // eslint-disable-next-line @next/next/no-img-element -- variants are pre-generated by the media pipeline
          <img
            src={mediaUrl(image, bestVariant(image, 1600))}
            srcSet={srcSet(image)}
            sizes={sizes}
            alt={image.alt}
            width={image.width}
            height={image.height}
            fetchPriority="high"
            decoding="async"
            className="absolute inset-0 h-full w-full object-cover"
            style={{ objectPosition: `${image.focalX}% ${image.focalY}%` }}
          />
        ) : null}
      </motion.div>
      {showVideo && (
        <button
          type="button"
          onClick={toggle}
          className="absolute bottom-4 right-4 inline-flex h-11 w-11 items-center justify-center rounded-full bg-ivory/80 text-ink backdrop-blur-sm transition-colors hover:bg-ivory"
          aria-label={paused ? "Play video" : "Pause video"}
        >
          {paused ? <Play size={16} weight="fill" aria-hidden /> : <Pause size={16} weight="fill" aria-hidden />}
        </button>
      )}
    </div>
  );
}
