import { bestVariant, mediaUrl, srcSet, type Media } from "@/lib/media";

type Props = {
  media: Media | null;
  sizes: string;
  className?: string;
  priority?: boolean;
  /** Fill the parent (object-fit cover, respecting the chosen focal point). */
  fill?: boolean;
  alt?: string;
};

/**
 * Responsive image from the media store. Falls back to a quiet, labelled
 * panel when the image is missing so layouts never collapse.
 */
export function MediaImage({ media, sizes, className = "", priority, fill = true, alt }: Props) {
  if (!media) {
    return (
      <div
        role="img"
        aria-label={alt ?? "Image coming soon"}
        className={`flex items-center justify-center bg-cream text-taupe ${fill ? "absolute inset-0" : "aspect-[4/5] w-full"} ${className}`}
      >
        <span className="eyebrow text-[0.65rem]">Image coming soon</span>
      </div>
    );
  }
  return (
    // eslint-disable-next-line @next/next/no-img-element -- variants are pre-generated by the media pipeline
    <img
      src={mediaUrl(media, bestVariant(media, 960))}
      srcSet={srcSet(media)}
      sizes={sizes}
      width={media.width}
      height={media.height}
      alt={alt ?? media.alt}
      loading={priority ? "eager" : "lazy"}
      fetchPriority={priority ? "high" : undefined}
      decoding="async"
      className={`${fill ? "absolute inset-0 h-full w-full object-cover" : "h-auto w-full"} ${className}`}
      style={{ objectPosition: `${media.focalX}% ${media.focalY}%` }}
    />
  );
}
